version: "3.8"
services:
  api:
    build:
      context: ./api/
      target: gobuilder
    ports:
      - 8080:8080
    volumes:
      - ./api:/app
    working_dir: /app
    depends_on:
      - db
    command: [ "./run.sh" ]
    networks:
      - ddd-go-network
  
  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ddd-go
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - ddd-go-network

networks:
  ddd-go-network:
    driver: bridge
